FROM data_processing:v3.0


# args mq_ip, mq_port , service_ip, service_port, type, thread_num
# type 0 cifar10
# type 1 cancer

CMD /data/start.sh 34.145.3.171 5672 http://istio-ingressgateway.istio-system 80 0 3
